"""add crash_events, sos_events, sos_event_audit_log

Revision ID: 0001_crash_and_sos_events
Revises:
Create Date: 2026-09-22

Hand-written (not autogenerated) — this repo's models had already drifted
from the live Supabase schema before any migration existed here, so a plain
`alembic revision --autogenerate` produces a few hundred unrelated diff
statements against existing tables (rides, ride_members, ride_locations,
ride_stops, etc.). This migration deliberately touches ONLY the three new
tables introduced by the Crash Detection and SOS Escalation architecture
docs, and does not attempt to reconcile that pre-existing drift.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001_crash_and_sos_events"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "sos_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("ride_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("rides.id"), nullable=False),
        sa.Column("user_id", sa.String(), sa.ForeignKey("profiles.id"), nullable=False),
        sa.Column("trigger_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False, server_default="sos_initiated"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_method", sa.String(), nullable=True),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("location_accuracy_m", sa.Float(), nullable=True),
        sa.Column("location_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location_is_stale", sa.Boolean(), server_default=sa.false()),
        sa.Column("speed_kph", sa.Float(), nullable=True),
        sa.Column("crash_confidence", sa.Float(), nullable=True),
        sa.Column("crash_peak_acceleration", sa.Float(), nullable=True),
        sa.Column("crash_rotation_change", sa.Float(), nullable=True),
        sa.Column("crash_stationary_duration_ms", sa.Integer(), nullable=True),
        sa.Column("response_provider", sa.String(), nullable=True),
        sa.Column("response_provider_event_id", sa.String(), nullable=True),
        sa.Column("response_operator_id", sa.String(), nullable=True),
        sa.Column("response_status", sa.String(), server_default="pending"),
        sa.Column("monitoring_unavailable", sa.Boolean(), server_default=sa.false()),
        sa.Column("resolution_outcome", sa.String(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_sos_events_ride_id", "sos_events", ["ride_id"])
    op.create_index("ix_sos_events_user_id", "sos_events", ["user_id"])
    op.create_index("ix_sos_events_status", "sos_events", ["status"])

    op.create_table(
        "sos_event_audit_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("sos_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("sos_events.id"), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("detail", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_sos_event_audit_log_sos_id", "sos_event_audit_log", ["sos_id"])

    op.create_table(
        "crash_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("ride_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("rides.id"), nullable=False),
        sa.Column("user_id", sa.String(), sa.ForeignKey("profiles.id"), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("location_accuracy_m", sa.Float(), nullable=True),
        sa.Column("location_age_s", sa.Float(), nullable=True),
        sa.Column("speed_kph", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("peak_acceleration", sa.Float(), nullable=True),
        sa.Column("rotation_change", sa.Float(), nullable=True),
        sa.Column("stationary_duration_s", sa.Float(), nullable=True),
        sa.Column("device_platform", sa.String(), nullable=True),
        sa.Column("device_os_version", sa.String(), nullable=True),
        sa.Column("sampling_rate_achieved", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), server_default="crash_suspected"),
        sa.Column("sos_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("sos_events.id"), nullable=True),
    )
    op.create_index("ix_crash_events_ride_id", "crash_events", ["ride_id"])
    op.create_index("ix_crash_events_user_id", "crash_events", ["user_id"])


def downgrade() -> None:
    op.drop_index("ix_crash_events_user_id", table_name="crash_events")
    op.drop_index("ix_crash_events_ride_id", table_name="crash_events")
    op.drop_table("crash_events")

    op.drop_index("ix_sos_event_audit_log_sos_id", table_name="sos_event_audit_log")
    op.drop_table("sos_event_audit_log")

    op.drop_index("ix_sos_events_status", table_name="sos_events")
    op.drop_index("ix_sos_events_user_id", table_name="sos_events")
    op.drop_index("ix_sos_events_ride_id", table_name="sos_events")
    op.drop_table("sos_events")
